### ISSUE TITLE
Missing auto-reflect magic name

### ISSUE THREAD

**Issue by Wisdomb33r** [aEnigmatic/ffbe-gl-strings#1]
Hi aEnigma,
I do not find any entry in MAGIC_NAME file for spell "30371", activated at battle start of when revived by "230914", which is passive of equipment "409030200".
Did you forgot to commit this file or is it a data problem located within the game ?
THank you in advance for your answer and cheers !
Wis

**Comment by Wisdomb33r** [comment]
Have the same problem with Decoding Googles today. Passive 913313 has correctly an entry in ABILITY_NAME file, but the activated 913315 (active at turn start while Doc Aiden / Agent Olive are alive) is missing.
Any idea ?

**Comment by aEnigmatic** [comment]
Sorry, for the late response. Those skills simply do not have any additional localization data in the game files except the raw name in the skill definition (which would default to the JP name for alim data).

**Comment by Wisdomb33r** [comment]
All right, I checked IG and this skill name is NOT displayed. The pop-up window only shows the name of the passive, which has the french translation correctly. 
I guess I'll have to use the raw name as a default value in my french parser too, so it does not crash and use a JP or EN name instead.
Thank you for the answer !
